//! Cargo utility for installing a workspace-local `project-root` proxy.
//!
//! Run `cargo project-root-patch install <path>` once in a consuming workspace.
//! See the [README](https://github.com/milyin/project-root-patch#readme) for the
//! generated layout and the crates.io-only vendoring procedure.

use std::{
    env,
    ffi::OsString,
    fs,
    path::{Path, PathBuf},
    process::Command,
};

use anyhow::{anyhow, bail, Context, Result};
use tempfile::TempDir;
use toml_edit::{Array, DocumentMut, Item, Table, Value};

const GENERATED_MARKER: &str = ".project-root-patch-generated";
const UPSTREAM_NAME: &str = "project-root";
const UPSTREAM_VERSION: &str = "0.2.2";
const VENDORED_DIR_NAME: &str = "project-root-0.2.2";

const PROXY_BUILD_RS: &str = r#"#[path = "upstream/project-root-0.2.2/src/lib.rs"]
mod upstream_project_root;

fn main() {
    let root = upstream_project_root::get_project_root()
        .expect("failed to determine the consuming workspace root");
    println!("cargo:rustc-env=PROJECT_ROOT={}", root.display());
}
"#;

const PROXY_LIB_RS: &str = r#"use std::{io, path::PathBuf};

/// Returns the absolute path to the consuming Cargo workspace root.
pub fn get_project_root() -> io::Result<PathBuf> {
    Ok(env!("PROJECT_ROOT").into())
}
"#;

const USAGE: &str = "project-root-patch

Usage:
    cargo project-root-patch install <path>
    cargo project-root-patch --version

Commands:
    help                 Show this help
    install <path>       Inject a local project-root proxy into a Cargo workspace

Details:
    <path> may be a package or workspace directory, or its Cargo.toml.
    A standalone package is converted into a workspace containing itself.
    Installation vendors project-root 0.2.2 through Cargo's configured registry.
";

fn main() {
    if let Err(err) = real_main() {
        eprintln!("error: {err:#}");
        std::process::exit(1);
    }
}

fn real_main() -> Result<()> {
    let mut args = env::args().skip(1).collect::<Vec<_>>();

    if let Some(first) = args.first().map(String::as_str) {
        if matches!(first, "project-root-patch" | "cargo-project-root-patch") {
            let _ = args.remove(0);
        }
    }

    if args.is_empty()
        || matches!(
            args.first().map(String::as_str),
            Some("help" | "-h" | "--help")
        )
    {
        println!("{USAGE}");
        return Ok(());
    }

    if matches!(args.first().map(String::as_str), Some("-V" | "--version")) {
        if args.len() != 1 {
            bail!("--version does not accept arguments");
        }
        println!("project-root-patch {}", env!("CARGO_PKG_VERSION"));
        return Ok(());
    }

    match args.remove(0).as_str() {
        "install" => {
            if args.len() != 1 {
                bail!("install requires exactly one <path>\n\n{USAGE}");
            }
            install(Path::new(&args[0]))
        }
        other => bail!("unknown command: {other}\n\n{USAGE}"),
    }
}

fn install(input: &Path) -> Result<()> {
    let workspace = resolve_workspace(input)?;
    let proxy_dir = workspace.root.join("project-root-patch");

    validate_destination(&proxy_dir)?;
    let workspace_manifest =
        render_workspace_manifest(&workspace.manifest, &proxy_dir, workspace.add_root_package)?;
    let upstream_dir = proxy_dir.join("upstream").join(VENDORED_DIR_NAME);
    let vendored = if valid_upstream_source(&upstream_dir) {
        None
    } else {
        Some(vendor_upstream()?)
    };

    fs::create_dir_all(proxy_dir.join("src"))
        .with_context(|| format!("creating proxy directory {}", proxy_dir.display()))?;

    if let Some(vendored) = vendored {
        let upstream_parent = proxy_dir.join("upstream");
        if upstream_parent.exists() {
            fs::remove_dir_all(&upstream_parent)
                .with_context(|| format!("removing {}", upstream_parent.display()))?;
        }
        copy_dir_all(&vendored.source, &upstream_dir).with_context(|| {
            format!(
                "copying vendored {UPSTREAM_NAME} {UPSTREAM_VERSION} to {}",
                upstream_dir.display()
            )
        })?;
    }

    fs::write(proxy_dir.join("Cargo.toml"), proxy_manifest())
        .with_context(|| format!("writing {}", proxy_dir.join("Cargo.toml").display()))?;
    fs::write(proxy_dir.join("src/lib.rs"), PROXY_LIB_RS)
        .with_context(|| format!("writing {}", proxy_dir.join("src/lib.rs").display()))?;
    fs::write(proxy_dir.join("build.rs"), PROXY_BUILD_RS)
        .with_context(|| format!("writing {}", proxy_dir.join("build.rs").display()))?;
    fs::write(
        proxy_dir.join(GENERATED_MARKER),
        format!(
            "generated by project-root-patch {}; upstream {UPSTREAM_NAME} {UPSTREAM_VERSION}\n",
            env!("CARGO_PKG_VERSION")
        ),
    )
    .with_context(|| format!("writing {}", proxy_dir.join(GENERATED_MARKER).display()))?;

    fs::write(&workspace.manifest, workspace_manifest)
        .with_context(|| format!("writing {}", workspace.manifest.display()))?;

    println!(
        "Installed local '{UPSTREAM_NAME}' proxy at: {}\nUsing vendored {UPSTREAM_NAME} {UPSTREAM_VERSION}\nUpdated workspace at: {}",
        proxy_dir.display(),
        workspace.manifest.display()
    );
    Ok(())
}

fn valid_upstream_source(source: &Path) -> bool {
    source.join("Cargo.toml").is_file()
        && source.join("src/lib.rs").is_file()
        && source.join(".cargo-checksum.json").is_file()
}

fn proxy_manifest() -> String {
    format!(
        r#"[package]
name = "project-root"
version = "{UPSTREAM_VERSION}"
edition = "2021"
license = "MIT OR Apache-2.0"
description = "Workspace-local proxy generated by project-root-patch"
publish = false
"#
    )
}

struct VendoredUpstream {
    _temp: TempDir,
    source: PathBuf,
}

fn vendor_upstream() -> Result<VendoredUpstream> {
    let temp = tempfile::Builder::new()
        .prefix("project-root-patch-vendor-")
        .tempdir()
        .context("creating temporary vendor directory")?;
    let manifest = temp.path().join("Cargo.toml");
    let placeholder = temp.path().join("lib.rs");
    fs::write(&placeholder, "").with_context(|| format!("writing {}", placeholder.display()))?;
    fs::write(
        &manifest,
        format!(
            r#"[package]
name = "project-root-patch-vendor"
version = "0.0.0"
edition = "2021"

[lib]
path = "lib.rs"

[dependencies]
project-root = "={UPSTREAM_VERSION}"

[workspace]
"#
        ),
    )
    .with_context(|| format!("writing {}", manifest.display()))?;

    let vendor_dir = temp.path().join("vendor");
    let cargo = env::var_os("CARGO").unwrap_or_else(|| OsString::from("cargo"));
    let output = Command::new(cargo)
        .arg("vendor")
        .arg("--manifest-path")
        .arg(&manifest)
        .arg("--versioned-dirs")
        .arg(&vendor_dir)
        .output()
        .context("running cargo vendor")?;
    if !output.status.success() {
        bail!(
            "cargo vendor failed:\n{}",
            String::from_utf8_lossy(&output.stderr).trim()
        );
    }

    let source = vendor_dir.join(VENDORED_DIR_NAME);
    if !source.join("Cargo.toml").is_file() || !source.join("src/lib.rs").is_file() {
        bail!(
            "cargo vendor did not produce the expected source directory: {}",
            source.display()
        );
    }

    Ok(VendoredUpstream {
        _temp: temp,
        source,
    })
}

fn copy_dir_all(source: &Path, destination: &Path) -> std::io::Result<()> {
    fs::create_dir_all(destination)?;
    for entry in fs::read_dir(source)? {
        let entry = entry?;
        let source_path = entry.path();
        let destination_path = destination.join(entry.file_name());
        let file_type = entry.file_type()?;
        if file_type.is_dir() {
            copy_dir_all(&source_path, &destination_path)?;
        } else if file_type.is_file() {
            fs::copy(source_path, destination_path)?;
        }
    }
    Ok(())
}

struct Workspace {
    root: PathBuf,
    manifest: PathBuf,
    add_root_package: bool,
}

fn resolve_workspace(input: &Path) -> Result<Workspace> {
    let manifest = if input.is_dir() {
        input.join("Cargo.toml")
    } else {
        input.to_path_buf()
    };
    if !manifest.exists() {
        bail!("path does not exist: {}", manifest.display());
    }
    if manifest.is_dir() {
        bail!(
            "expected a Cargo.toml file or a directory containing one: {}",
            manifest.display()
        );
    }

    let text =
        fs::read_to_string(&manifest).with_context(|| format!("reading {}", manifest.display()))?;
    let doc: DocumentMut = text
        .parse()
        .with_context(|| format!("parsing TOML at {}", manifest.display()))?;

    if doc.contains_key("workspace") {
        let root = manifest
            .parent()
            .ok_or_else(|| anyhow!("manifest has no parent: {}", manifest.display()))?
            .to_path_buf();
        return Ok(Workspace {
            root,
            manifest,
            add_root_package: false,
        });
    }

    if doc.contains_key("package") {
        if let Some(workspace_manifest) =
            find_ancestor_workspace_manifest(manifest.parent().unwrap())?
        {
            return Ok(Workspace {
                root: workspace_manifest.parent().unwrap().to_path_buf(),
                manifest: workspace_manifest,
                add_root_package: false,
            });
        }
        return Ok(Workspace {
            root: manifest.parent().unwrap().to_path_buf(),
            manifest,
            add_root_package: true,
        });
    }

    bail!(
        "{} is not a valid Cargo manifest (neither [workspace] nor [package] found)",
        manifest.display()
    )
}

fn validate_destination(proxy_dir: &Path) -> Result<()> {
    if !proxy_dir.exists() {
        return Ok(());
    }
    if !proxy_dir.is_dir() {
        bail!(
            "target path exists and is not a directory: {}",
            proxy_dir.display()
        );
    }
    if !proxy_dir.join(GENERATED_MARKER).is_file() {
        bail!(
            "refusing to overwrite unrecognized directory: {}\n\
             Move or remove it after verifying its contents, then run the command again.",
            proxy_dir.display()
        );
    }
    Ok(())
}

fn find_ancestor_workspace_manifest(start_dir: &Path) -> Result<Option<PathBuf>> {
    let mut current = Some(start_dir);
    while let Some(dir) = current {
        let candidate = dir.join("Cargo.toml");
        if candidate.exists() {
            let text = fs::read_to_string(&candidate)
                .with_context(|| format!("reading {}", candidate.display()))?;
            let doc: DocumentMut = match text.parse() {
                Ok(document) => document,
                Err(_) => {
                    current = dir.parent();
                    continue;
                }
            };
            if doc.contains_key("workspace") {
                return Ok(Some(candidate));
            }
        }
        current = dir.parent();
    }
    Ok(None)
}

fn render_workspace_manifest(
    workspace_manifest: &Path,
    proxy_dir: &Path,
    add_root_package: bool,
) -> Result<String> {
    let text = fs::read_to_string(workspace_manifest)
        .with_context(|| format!("reading {}", workspace_manifest.display()))?;
    let mut doc: DocumentMut = text
        .parse()
        .with_context(|| format!("parsing TOML at {}", workspace_manifest.display()))?;

    let workspace = doc["workspace"].or_insert(Item::Table(Table::new()));
    let workspace = workspace
        .as_table_mut()
        .ok_or_else(|| anyhow!("[workspace] must be a TOML table"))?;

    let members = workspace
        .entry("members")
        .or_insert(Item::Value(Value::Array(Array::default())))
        .as_array_mut()
        .ok_or_else(|| anyhow!("workspace.members must be an array"))?;
    if add_root_package && !contains(members, ".") {
        members.push(".");
    }
    if !contains(members, "project-root-patch") {
        members.push("project-root-patch");
    }

    let excluded_upstream = format!("project-root-patch/upstream/{VENDORED_DIR_NAME}");
    let exclude = workspace
        .entry("exclude")
        .or_insert(Item::Value(Value::Array(Array::default())))
        .as_array_mut()
        .ok_or_else(|| anyhow!("workspace.exclude must be an array"))?;
    if !contains(exclude, &excluded_upstream) {
        exclude.push(excluded_upstream);
    }

    let patch = doc["patch"].or_insert(Item::Table(Table::new()));
    let patch = patch
        .as_table_mut()
        .ok_or_else(|| anyhow!("[patch] must be a TOML table"))?;
    let crates_io = patch
        .entry("crates-io")
        .or_insert(Item::Table(Table::new()))
        .as_table_mut()
        .ok_or_else(|| anyhow!("[patch.crates-io] must be a TOML table"))?;

    crates_io.remove("project-root-patch");
    let relative_proxy = pathdiff::diff_paths(proxy_dir, workspace_manifest.parent().unwrap())
        .unwrap_or_else(|| proxy_dir.to_path_buf());
    let relative_proxy = relative_proxy.to_string_lossy().replace('\\', "/");
    let mut path_table = Table::new();
    path_table.insert("path", toml_edit::value(relative_proxy));
    crates_io.insert(UPSTREAM_NAME, Item::Table(path_table));

    Ok(doc.to_string())
}

fn contains(array: &Array, expected: &str) -> bool {
    array.iter().any(|value| value.as_str() == Some(expected))
}
