use std::{
    env, fs,
    path::{Path, PathBuf},
};

use anyhow::{anyhow, bail, Context, Result};
use toml_edit::{Array, DocumentMut, Item, Table, Value};

const GENERATED_MARKER: &str = ".project-root-patch-generated";

const USAGE: &str = "project-root-patch

Usage:
    cargo project-root-patch install <path>
    cargo project-root-patch --version

Commands:
    help                 Show this help
    install <path>       Inject project-root-patch into a Cargo workspace

Details:
    <path> may be a package or workspace directory, or its Cargo.toml.
    A standalone package is converted into a workspace containing itself.
";

fn main() {
    if let Err(err) = real_main() {
        eprintln!("error: {:#}", err);
        std::process::exit(1);
    }
}

fn real_main() -> Result<()> {
    let mut args = env::args().skip(1).collect::<Vec<_>>();

    if let Some(first) = args.first().map(|s| s.as_str()) {
        if matches!(first, "project-root-patch" | "cargo-project-root-patch") {
            let _ = args.remove(0);
        }
    }

    if args.is_empty()
        || matches!(
            args.first().map(|s| s.as_str()),
            Some("help" | "-h" | "--help")
        )
    {
        println!("{}", USAGE);
        return Ok(());
    }

    if matches!(args.first().map(String::as_str), Some("-V" | "--version")) {
        if args.len() != 1 {
            bail!("--version does not accept arguments");
        }
        println!("project-root-patch {}", env!("CARGO_PKG_VERSION"));
        return Ok(());
    }

    match args.remove(0).as_str() {
        "install" => {
            if args.len() != 1 {
                bail!("install requires exactly one <path>\n\n{USAGE}");
            }
            install(Path::new(&args[0]))
        }
        other => bail!("unknown command: {}\n\n{}", other, USAGE),
    }
}

fn install(input: &Path) -> Result<()> {
    let workspace = resolve_workspace(input)?;
    let local_crate_dir = workspace.root.join("project-root-patch");

    validate_destination(&local_crate_dir)?;
    let workspace_manifest = render_workspace_manifest(
        &workspace.manifest,
        &local_crate_dir,
        workspace.add_root_package,
    )?;

    fs::create_dir_all(local_crate_dir.join("src"))
        .with_context(|| format!("creating crate dir {}", local_crate_dir.display()))?;

    let local_cargo = local_crate_dir.join("Cargo.toml");
    let version = env!("CARGO_PKG_VERSION");
    let cargo_toml = format!(
        r#"[package]
name = "project-root-patch"
version = "{version}"
edition = "2021"
license = "MIT OR Apache-2.0"
description = "Utility to expose the workspace project root at build time"
publish = false

[build-dependencies]
project-root = "0.2"
"#
    );
    fs::write(&local_cargo, cargo_toml)
        .with_context(|| format!("writing {}", local_cargo.display()))?;

    let lib_rs = include_str!("./lib.rs");
    let build_rs = include_str!("../build.rs");

    fs::write(local_crate_dir.join("src/lib.rs"), lib_rs)
        .with_context(|| format!("writing {}", local_crate_dir.join("src/lib.rs").display()))?;
    fs::write(local_crate_dir.join("build.rs"), build_rs)
        .with_context(|| format!("writing {}", local_crate_dir.join("build.rs").display()))?;
    fs::write(
        local_crate_dir.join(GENERATED_MARKER),
        format!("generated by project-root-patch {version}\n"),
    )
    .with_context(|| {
        format!(
            "writing {}",
            local_crate_dir.join(GENERATED_MARKER).display()
        )
    })?;

    fs::write(&workspace.manifest, workspace_manifest)
        .with_context(|| format!("writing {}", workspace.manifest.display()))?;

    println!(
        "Installed local 'project-root-patch' crate at: {}\nUpdated workspace at: {}",
        local_crate_dir.display(),
        workspace.manifest.display()
    );
    Ok(())
}

struct Workspace {
    root: PathBuf,
    manifest: PathBuf,
    add_root_package: bool,
}

fn resolve_workspace(input: &Path) -> Result<Workspace> {
    let p = if input.is_dir() {
        input.join("Cargo.toml")
    } else {
        input.to_path_buf()
    };
    if !p.exists() {
        bail!("Path does not exist: {}", p.display());
    }
    if p.is_dir() {
        bail!(
            "Expected a Cargo.toml file or a directory containing one: {}",
            p.display()
        );
    }

    let text = fs::read_to_string(&p).with_context(|| format!("reading {}", p.display()))?;
    let doc: DocumentMut = text
        .parse()
        .with_context(|| format!("parsing TOML at {}", p.display()))?;

    if doc.contains_key("workspace") {
        let root = p
            .parent()
            .ok_or_else(|| anyhow!("manifest has no parent: {}", p.display()))?
            .to_path_buf();
        return Ok(Workspace {
            root,
            manifest: p,
            add_root_package: false,
        });
    }

    if doc.contains_key("package") {
        if let Some(ws_manifest) = find_ancestor_workspace_manifest(p.parent().unwrap())? {
            return Ok(Workspace {
                root: ws_manifest.parent().unwrap().to_path_buf(),
                manifest: ws_manifest,
                add_root_package: false,
            });
        }
        return Ok(Workspace {
            root: p.parent().unwrap().to_path_buf(),
            manifest: p,
            add_root_package: true,
        });
    }

    bail!(
        "{} is not a valid Cargo manifest (neither [workspace] nor [package] found)",
        p.display()
    )
}

fn validate_destination(local_crate_dir: &Path) -> Result<()> {
    if !local_crate_dir.exists() {
        return Ok(());
    }
    if !local_crate_dir.is_dir() {
        bail!(
            "target path exists and is not a directory: {}",
            local_crate_dir.display()
        );
    }
    if !local_crate_dir.join(GENERATED_MARKER).is_file() {
        bail!(
            "refusing to overwrite unrecognized directory: {}\n\
             Move or remove it after verifying its contents, then run the command again.",
            local_crate_dir.display()
        );
    }
    Ok(())
}

fn find_ancestor_workspace_manifest(start_dir: &Path) -> Result<Option<PathBuf>> {
    let mut cur = Some(start_dir);
    while let Some(dir) = cur {
        let cand = dir.join("Cargo.toml");
        if cand.exists() {
            let text =
                fs::read_to_string(&cand).with_context(|| format!("reading {}", cand.display()))?;
            let doc: DocumentMut = match text.parse() {
                Ok(d) => d,
                Err(_) => {
                    // Not valid TOML; skip
                    cur = dir.parent();
                    continue;
                }
            };
            if doc.contains_key("workspace") {
                return Ok(Some(cand));
            }
        }
        cur = dir.parent();
    }
    Ok(None)
}

fn render_workspace_manifest(
    ws_manifest_path: &Path,
    local_crate_dir: &Path,
    add_root_package: bool,
) -> Result<String> {
    let text = fs::read_to_string(ws_manifest_path)
        .with_context(|| format!("reading {}", ws_manifest_path.display()))?;
    let mut doc: DocumentMut = text
        .parse()
        .with_context(|| format!("parsing TOML at {}", ws_manifest_path.display()))?;

    let ws = doc["workspace"].or_insert(Item::Table(Table::new()));
    let ws_tbl = ws
        .as_table_mut()
        .ok_or_else(|| anyhow!("[workspace] must be a TOML table"))?;

    let members = ws_tbl
        .entry("members")
        .or_insert(Item::Value(Value::Array(Array::default())));
    let members = members
        .as_array_mut()
        .ok_or_else(|| anyhow!("workspace.members must be an array"))?;
    if add_root_package && !members.iter().any(|value| value.as_str() == Some(".")) {
        members.push(".");
    }
    if !members
        .iter()
        .any(|value| value.as_str() == Some("project-root-patch"))
    {
        members.push("project-root-patch");
    }

    let patch = doc["patch"].or_insert(Item::Table(Table::new()));
    let patch_tbl = patch
        .as_table_mut()
        .ok_or_else(|| anyhow!("[patch] must be a TOML table"))?;
    let crates_io = patch_tbl
        .entry("crates-io")
        .or_insert(Item::Table(Table::new()));
    let crates_io_tbl = crates_io
        .as_table_mut()
        .ok_or_else(|| anyhow!("[patch.crates-io] must be a TOML table"))?;

    let rel_path = pathdiff::diff_paths(local_crate_dir, ws_manifest_path.parent().unwrap())
        .unwrap_or_else(|| local_crate_dir.to_path_buf());
    let rel_str = rel_path.to_string_lossy().replace('\\', "/");

    let mut path_table = Table::new();
    path_table.insert("path", toml_edit::value(rel_str));
    crates_io_tbl.insert("project-root-patch", Item::Table(path_table));

    Ok(doc.to_string())
}
